// AUTO-GENERATED by scripts/svg-paths.ts — do not edit manually

export const DRAWING_CIRCUIT: Record<string, string> = {
	path3: 'l4.5o4.5 i r.25i.5 i.5 r.25i.5 i1.5 i1.5 l.25i.5 i1.75 l.25i.75 i.5',
	path2:
		'l4o4.5 i.75 r.25i.5 i.5 r.25i.5 i1.25f0 r.5i.5b.71 l.5i.5t0 i1.25 l.25i.5 i1.75 l.25i.75 i.25',
	path4:
		'l3.5o4.5 i.75 r.25i.5 i.5 r.25i.5 i.75f0 r.5ib.67 l.5i.9t0 i.85 l.25i.5 i1.75 l.25i.75 i.25',
	path5:
		'l3o4.5 i.75 r.25i.5 i.5 r.25i.5 i.5f0 r.5i1.25b.74 l.5i1.25t0 i.5 l.25i.5 i1.75 l.25i.75 i.25',
	path6:
		'l2.5o4.5 i.75 r.25i.5 i.5 r.25i.5 i.25 r.25i.25f.28 r.25i1.25t.39 i.75 l.25i.5 r.25 i.5 l.5 l.25i.5 i1.75 l.25i.75 i.25',
	path7:
		'l2o4.5 i.75 r.25i.5 i.5 r.25i.5 r.25 i.5 r.5i.75 l.5 i1.25 r.25i.5 l.25 i.5 r.25i.25 i.25 l.75 i.25 i1.5 l.25i.75 i.25',
	path1: 'r4 l.01o r.25o.5 o1.75 r.25o.75 o.5',
	path8: 'r4.49i4.5 o l.25o.5 o.5 l.25o.5 r.01o',
	path9:
		'r3.99i4.5 o.75 l.25o.5 o.5 l.25o.5 o1.25f0 l.5o.5b.71 r.5o.5t0 o1.25 r.25o.5 o1.75 r.25o.75 o.25',
	path10:
		'r3.49i4.5 o.75 l.25o.5 o.5 l.25o.5 o.75 l.49o.25 o1.37 r.49o.28 o.85 r.25o.5 o1.75 r.25o.75 o.25',
	path11:
		'r2.99i4.5 o.75 l.25o.5 o.5 l.25o.5 r.01o.5 l.51o.25 o1.75 r.51o.5 l.01o.5 r.25o.5 o1.75 r.25o.75 o.25',
	path21: 'r2o r.25o.75 l.01o1.75 r.25o.75 o.25',
	path12: 'r2.49i4.5 r.01o.75 l.5o.75 o',
	path13:
		'r1.5i4.5 o.5 l.5o.5 o1.15f.37 r.62o.35b.41 l.75o.49b.42 r.75o.5b.42 l.75o.5b.43 r.75o.5b.43 l.73o.5b.43 r.73o.5b.43 l.75o.5b.42 r.88o.32t.29 l.01o1.68 r.25o.75 o.25',
	path14:
		'l.48 o3.81f.42 l1.19o1.19t.42 l2.83f.35 l.5i.5t.35 i9f.35 r.5i.5t.35 r3.31f.42 r1.19o1.19t.42 o7.62f.42 r1.19o1.19t.42 r3.31f.35 r.5i.5t.35 i9f.35 l.5i.5t.35 l2.83f.42 l1.19o1.19t.42 o3.81',
	path15: 'r1.5o4.5 l.75i.5 r.5i.5 i l.75o.75 i2.25',
	path16: 'l1.5o4.5 i.75 r.5i.25 i.75',
	path17: 'l1.5i4.5 r.25o.75 r.5i.25 l.5o1.75 r.75i o2.25',
	path18: 'r2i4.5 o.75 l.5o.5 o.5',
	path19: 'r4.5o i2 l.5o.5 l.5',
	path20: 'l4.5o2 i3'
}

export const DRAWING_RAVEN: Record<string, string> = {
	path20: 'l.25o2.8 o1.5 l.5o.5 i2 r.5',
	path1: 'l1.1o2.8 l.75o1.3 l.68o.18 ri1.73 r.43o.25',
	path2: 'r.25o2.8 o1.5 r.5o.5 i2 l.5',
	path3: 'ro2.8 r.75o1.3 r.68o.18 li1.73 l.43o.25',
	path4: 'ro1.55 o l2 i r2',
	path5: 'r.75o1.8 o.5 l1.5 i.5 r1.5',
	path6: 'r.5o1.25 l i2 r o2',
	path7: 'r.25o l.5 i1.5 r.5 o1.5',
	path8: 'r2.25i.5 r.75o1.3 r.68o.18 l1i1.73 l.43o.25',
	path9: 'r1.5i.5 r.39o1.45 r.61o.35 l.52i1.93 l.48o.13',
	path10: 'r.75i.75 o1.5 r.5o.5 i2 l.5',
	path11: 'r3i.5 r1.06o1.06 r.71 l1.41i1.41 l.35o.35',
	path12: 'l2.25i.5 l.75o1.3 l.68o.18 ri1.73 r.43o.25',
	path13: 'l1.5i.5 l.39o1.45 l.61o.35 r.52i1.93 r.48o.13',
	path14: 'l.75i.75 o1.5 l.5o.5 i2 r.5',
	path15: 'l3i.5 l1.06o1.06 l.71 r1.41i1.41 r.35o.35',
	path16: 'l1.17i2.9 l1.5o0 l.5i.5 r2 o.5',
	path17: 'l.38i2.56 l1.06o1.06 l.71 r1.41i1.41 r.35o.35',
	path18: 'l2i2.25f.39 l.5o.5b.39 l.5i.5b.39 r.5i.5b.39 r.5o.5t.39',
	path19: 'r.25i3.6f.39 l.5o.5b.39 l.5i.5b.39 r.5i.5b.39 r.5o.5t.39',
	path21: 'r.5i l i.75 ri o1.75',
	path22: 'ri4 r1.5 r.5i.5 l2 o.5',
	path23: 'ri3.2 r.88 r.5i.5 l1.13 l.25 o.5',
	path46:
		'r.59i4.71 l.36o.28 l1.02i.04 l.42o.66 l2.94 r.89o1.06 o.25 l.25o.25 r.25o.5 l.11o.32 l2.38o2.38 r1.6 l.38o.66 r1.63i.44 l.25o.95 r1.49i.86 o.85 l1.61o2.79 r1.78i.48 r.34i.58 o1.91 r1.15i1.15 r1.15o1.15 i1.91 r.34o.58 r1.78o.48 l1.61i2.79 i.85 r1.49o.86 l.25i.95 r1.63o.44 l.38i.66 r1.6 l2.38i2.38 l.38o.38 l.15i.25 l.53o.31 l.08i.12 l.57o.15 i.2 l.75 i1.65 r1.14 r1.29i1.29 l.17i.01 r.8i.8 l3.37 o.2',
	path47: 'l1.15o6 o1.91 r1.15i1.15 r1.15o1.15 i1.91 l2.3',
	path49: 'l1.15o8 o1.91 r1.15i1.15 r1.15o1.15 i1.91 l2.3',
	path50: 'l1.15o9.99 o1.91 r1.15i1.15 r1.15o1.15 i1.91 l2.3',
	path24: 'ro1.55 o l2 i r2'
}

export const DRAWING_FORMLINES: Record<string, string> = {
	OO: 'r4.75f.54 l1.5o.95b.47 l1.5i.95b.54 r1.5i.95b.47 r1.5o.95t.54',
	OI: 'r4f.58 l.97o.7b.45 l.98i.7b.58 r.98i.7b.45 r.97o.7t.58',
	SRR: 'r1.25i1f0 l.5o.25b.33 l.75o1.25b.28 lo0b0 r.5i.25b.6 r.75i1.25b.28 ri0t0',
	SR: 'l.5if0 l.5o.25b.33 l.75o1.25t.28 lo0f0 r.5i.25b.6 r.75i1.25t.28 r',
	S: 'l2.25i l.5o.25 l.75o1.25 lo0 r.5i.25 r.75i1.25 r'
}

export default { DRAWING_CIRCUIT, DRAWING_RAVEN, DRAWING_FORMLINES }
