// Scans resources/midi/**/*.mid and writes src/scenes/utils/midi-notes.ts
// Each MIDI file → typed note data (note/velocity/duration/time in ms) per track
import { readdirSync, statSync, readFileSync, writeFileSync } from 'fs'
import { join, basename, extname } from 'path'
import { createRequire } from 'module'
const { Midi } = createRequire(import.meta.url)('@tonejs/midi') as typeof import('@tonejs/midi')

const midiDir = new URL('../resources/midi', import.meta.url).pathname
const outFile = new URL('../src/scenes/utils/midi-notes.ts', import.meta.url).pathname

function findMidi(dir: string): string[] {
	const entries: string[] = []
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry)
		if (statSync(full).isDirectory()) {
			entries.push(...findMidi(full))
		} else if (extname(entry) === '.mid' || extname(entry) === '.midi') {
			entries.push(full)
		}
	}
	return entries
}

function toKey(filename: string): string {
	return basename(filename).replace(/\.(mid|midi)$/, '')
}

function parseMidi(filePath: string) {
	const buf = readFileSync(filePath)
	const midi = new Midi(buf)
	const bpm = midi.header.tempos[0]?.bpm ?? 120
	const timeSig = midi.header.timeSignatures[0]
	const num = timeSig?.timeSignature[0] ?? 4
	const den = timeSig?.timeSignature[1] ?? 4

	const tracks = midi.tracks.map((track) => {
		const notes = track.notes.map((n) => ({
			note: n.midi,
			velocity: Math.round(n.velocity * 127),
			duration: Math.round(n.duration * 1000),
			time: Math.round(n.time * 1000)
		}))
		return {
			name: track.name,
			notes,
			durationMs: notes.length > 0 ? Math.max(...notes.map((n) => n.time + n.duration)) : 0
		}
	})

	return { bpm, timeSig: [num, den] as [number, number], tracks }
}

function serialize(data: Record<string, ReturnType<typeof parseMidi>>): string {
	const entries = Object.entries(data)
		.map(([key, file]) => {
			const tracks = file.tracks
				.map((track) => {
					const notes = track.notes
						.map(
							(n) =>
								`{ note: ${n.note}, velocity: ${n.velocity}, duration: ${n.duration}, time: ${n.time} }`
						)
						.join(',\n\t\t\t\t')
					return `{
\t\t\t\tname: ${JSON.stringify(track.name)},
\t\t\t\tdurationMs: ${track.durationMs},
\t\t\t\tnotes: [\n\t\t\t\t\t${notes}\n\t\t\t\t],
\t\t\t}`
				})
				.join(',\n\t\t\t')
			return `\t${JSON.stringify(key)}: {
\t\t\tbpm: ${file.bpm},
\t\t\ttimeSig: [${file.timeSig[0]}, ${file.timeSig[1]}] as [number, number],
\t\t\ttracks: [\n\t\t\t\t${tracks}\n\t\t\t],
\t\t}`
		})
		.join(',\n')

	return `// AUTO-GENERATED by scripts/midi-notes.ts — do not edit manually
/* eslint-disable unicorn/numeric-separators-style */

export type MidiNote = {
\tnote: number
\tvelocity: number
\tduration: number
\ttime: number
}

export type MidiTrackData = {
\tname: string
\tnotes: MidiNote[]
\tdurationMs: number
}

export type MidiFileData = {
\tbpm: number
\ttimeSig: [number, number]
\ttracks: MidiTrackData[]
}

export const MIDI: Record<string, MidiFileData> = {
${entries}
}
`
}

const files = findMidi(midiDir)
if (files.length === 0) {
	console.log('No MIDI files found in', midiDir)
	process.exit(0)
}

const data: Record<string, ReturnType<typeof parseMidi>> = {}
for (const file of files) {
	const key = toKey(file)
	data[key] = parseMidi(file)
	const trackSummary = data[key].tracks
		.map((t) => `${t.name || '(unnamed)'} ${t.notes.length}n`)
		.join(', ')
	console.log(`  ${key}: ${data[key].tracks.length} tracks [${trackSummary}] @ ${data[key].bpm}bpm`)
}

writeFileSync(outFile, serialize(data))
console.log('Written:', outFile)
