// Scans public/patchers/**/*.json and writes src/lib/audio/patchers.ts
import { readdirSync, statSync, writeFileSync } from 'fs'
import { join, relative, basename, extname } from 'path'

const patchersDir = new URL('../public/patchers', import.meta.url).pathname
const outFile = new URL('../src/lib/audio/patchers.ts', import.meta.url).pathname

function findJson(dir, base) {
	const entries = []
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry)
		if (statSync(full).isDirectory()) {
			entries.push(...findJson(full, base))
		} else if (extname(entry) === '.json') {
			const rel = relative(base, full)
			const name = basename(entry, '.json')
			const subpath = rel.replace(/\.json$/, '')
			entries.push([name, subpath])
		}
	}
	return entries
}

const entries = findJson(patchersDir, patchersDir)
entries.sort((a, b) => a[0].localeCompare(b[0]))

const lines = entries.map(([name, path]) => `\t'${name}': '${path}',`)

const out = `// AUTO-GENERATED by scripts/patchers.js — do not edit manually
export const PATCHERS: Record<string, string> = {
${lines.join('\n')}
}
`

writeFileSync(outFile, out)
console.log(`Wrote ${entries.length} entries to ${outFile}`)
