// Scans public/samples/<instrument>/<note>.* and writes src/lib/audio/samples.ts
import { readdirSync, statSync, writeFileSync } from 'fs'
import { join, basename, extname } from 'path'

const samplesDir = new URL('../public/samples', import.meta.url).pathname
const outFile = new URL('../src/lib/audio/samples.ts', import.meta.url).pathname

const NOTE_ORDER = ['C', 'Cs', 'D', 'Ds', 'E', 'F', 'Fs', 'G', 'Gs', 'A', 'As', 'B']

function noteToMidi(name) {
	const m = name.match(/^([A-G][sb]?)(\d)$/)
	if (!m) return 999
	let n = NOTE_ORDER.indexOf(m[1])
	if (n === -1) {
		// handle flat aliases
		const flats = { Db: 1, Eb: 3, Gb: 6, Ab: 8, Bb: 10 }
		n = flats[m[1]] ?? 999
	}
	return (parseInt(m[2]) + 1) * 12 + n
}

const instruments = {}

for (const dir of readdirSync(samplesDir).sort()) {
	const full = join(samplesDir, dir)
	if (!statSync(full).isDirectory()) continue
	const notes = {}
	for (const file of readdirSync(full)) {
		const ext = extname(file)
		if (!ext) continue
		if (!['.wav', '.mp3', '.ogg'].includes(ext.toLowerCase())) continue
		const note = basename(file, ext).replace('s', '#')
		notes[note] = `${dir}/${file}`
	}
	// Sort notes by MIDI pitch
	const sorted = Object.entries(notes).sort((a, b) => noteToMidi(a[0]) - noteToMidi(b[0]))
	instruments[dir] = Object.fromEntries(sorted)
}

const lines = Object.entries(instruments).map(([inst, notes]) => {
	const noteLines = Object.entries(notes).map(([n, p]) => `\t\t'${n}': '${p}',`)
	return `\t'${inst}': {\n${noteLines.join('\n')}\n\t},`
})

const out = `// AUTO-GENERATED by scripts/samples.js — do not edit manually
export const SAMPLES: Record<string, Record<string, string>> = {
${lines.join('\n')}
}
`

writeFileSync(outFile, out)
console.log(`Wrote ${Object.keys(instruments).length} instruments to ${outFile}`)
