#!/usr/bin/env tsx
// Reads public/samples/<instrument>/samples.json sidecars (produced by sample-meta.ts)
// and writes src/lib/audio/samples.ts.
// Run `npm run gen:sample-meta` first to update sidecars, then `npm run gen:samples`.
import { readdirSync, statSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { join, basename, extname } from 'node:path'
import { AudioMeta, Sidecar, SidecarNote } from './lib/sidecars'

const samplesDir = new URL('../public/samples', import.meta.url).pathname
const outFile = new URL('../src/lib/audio/samples.ts', import.meta.url).pathname

// ---- Types (mirrored in generated output) -----------------------------------

type LoopEntry = { loopStartSample: number; loopEndSample: number; sampleRate: number }
type NoteEntry = { path: string; loop?: LoopEntry }
type MetaEntry = AudioMeta

// ---- Helpers ----------------------------------------------------------------

const NOTE_ORDER = ['C', 'Cs', 'D', 'Ds', 'E', 'F', 'Fs', 'G', 'Gs', 'A', 'As', 'B']
const AUDIO_EXTS = new Set(['.wav', '.mp3', '.ogg'])

function noteToMidi(name: string): number {
	const m = name.match(/^([A-G][sb]?)(\d)$/)
	if (!m) return 999
	let n = NOTE_ORDER.indexOf(m[1])
	if (n === -1) {
		const flats: Record<string, number> = { Db: 1, Eb: 3, Gb: 6, Ab: 8, Bb: 10 }
		n = flats[m[1]] ?? 999
	}
	return (parseInt(m[2]) + 1) * 12 + n
}

/** Format integer with underscore separators every 3 digits from the right. */
function fmtInt(n: number): string {
	const s = String(n)
	let out = ''
	for (let i = 0; i < s.length; i++) {
		if (i > 0 && (s.length - i) % 3 === 0) out += '_'
		out += s[i]
	}
	return out
}

function loopFromSidecar(sidecar: Sidecar, noteName: string): LoopEntry | undefined {
	const sr = sidecar.sampleRate
	if (!sr) return undefined

	const perNote: SidecarNote | undefined = sidecar.notes?.[noteName]
	if (perNote?.loopStartSample !== undefined && perNote?.loopEndSample !== undefined) {
		return {
			loopStartSample: perNote.loopStartSample,
			loopEndSample: perNote.loopEndSample,
			sampleRate: sr
		}
	}
	if (sidecar.loopStartSample !== undefined && sidecar.loopEndSample !== undefined) {
		return {
			loopStartSample: sidecar.loopStartSample,
			loopEndSample: sidecar.loopEndSample,
			sampleRate: sr
		}
	}
	return undefined
}

// ---- Scan -------------------------------------------------------------------

const instruments: Record<string, Record<string, NoteEntry>> = {}
const sampleMeta: Record<string, MetaEntry> = {}

for (const dir of readdirSync(samplesDir).sort()) {
	const full = join(samplesDir, dir)
	if (!statSync(full).isDirectory()) continue

	const sidecarPath = join(full, 'samples.json')
	let sidecar: Sidecar = {}
	if (existsSync(sidecarPath)) {
		try {
			sidecar = JSON.parse(readFileSync(sidecarPath, 'utf8')) as Sidecar
		} catch {}
	}

	if (sidecar.sampleRate && sidecar.duration) {
		sampleMeta[dir] = {
			sampleRate: sidecar.sampleRate,
			channels: sidecar.channels ?? 1,
			...(sidecar.bitDepth !== undefined ? { bitDepth: sidecar.bitDepth } : {}),
			duration: sidecar.duration, //.toFixed(4),
			samples: sidecar.samples ?? 0
		}
	}

	const notes: Record<string, NoteEntry> = {}
	for (const file of readdirSync(full)) {
		const ext = extname(file).toLowerCase()
		if (!AUDIO_EXTS.has(ext)) continue
		const noteName = basename(file, extname(file)).replace('s', '#')
		notes[noteName] = { path: `${dir}/${file}`, loop: loopFromSidecar(sidecar, noteName) }
	}

	instruments[dir] = Object.fromEntries(
		Object.entries(notes).sort((a, b) => noteToMidi(a[0]) - noteToMidi(b[0]))
	)
}

// ---- Serialize --------------------------------------------------------------

const samplesLines = Object.entries(instruments).map(([inst, notes]) => {
	const noteLines = Object.entries(notes).map(([n, entry]) => {
		if (entry.loop) {
			const { loopStartSample: ls, loopEndSample: le, sampleRate: sr } = entry.loop
			return `\t\t'${n}': { path: '${entry.path}', loop: { loopStartSample: ${fmtInt(ls)}, loopEndSample: ${fmtInt(le)}, sampleRate: ${fmtInt(sr)} } },`
		}
		return `\t\t'${n}': { path: '${entry.path}' },`
	})
	return `\t'${inst}': {\n${noteLines.join('\n')}\n\t},`
})

const metaLines = Object.entries(sampleMeta).map(([inst, m]) => {
	const bd = m.bitDepth !== undefined ? `, bitDepth: ${fmtInt(m.bitDepth)}` : ''
	return `\t'${inst}': { sampleRate: ${fmtInt(m.sampleRate)}, channels: ${m.channels}${bd}, duration: ${m.duration} },`
})

const output = `// AUTO-GENERATED by scripts/samples.ts — do not edit manually

export interface SampleLoopInfo {
\tloopStartSample: number
\tloopEndSample: number
\tsampleRate: number
}

export interface SampleMeta {
\tsampleRate: number
\tchannels: number
\tbitDepth?: number
\tduration: number
}

export interface SampleEntry {
\tpath: string
\tloop?: SampleLoopInfo
}

export const SAMPLE_META: Record<string, SampleMeta> = {
${metaLines.join('\n')}
}

export const SAMPLES: Record<string, Record<string, SampleEntry>> = {
${samplesLines.join('\n')}
}
`

writeFileSync(outFile, output)
console.log(`Wrote ${Object.keys(instruments).length} instruments to ${outFile}`)
