// Scans resources/svg/**/*.svg and writes src/scenes/utils/svg-paths.ts
// Each SVG file → one const with path `d` attributes parsed via svgRail + serialized with railToString
import { readdirSync, statSync, readFileSync, writeFileSync } from 'fs'
import { join, basename, extname } from 'path'
import { execSync } from 'child_process'
import { svgRail } from '../src/lib/core/rail-primitives'
import { railToString } from '../src/lib/core/rail-path'

const svgDir = new URL('../resources/svg', import.meta.url).pathname
const outFile = new URL('../src/scenes/utils/svg-paths.ts', import.meta.url).pathname

function findSvg(dir: string): string[] {
	const entries: string[] = []
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry)
		if (statSync(full).isDirectory()) {
			entries.push(...findSvg(full))
		} else if (extname(entry) === '.svg') {
			entries.push(full)
		}
	}
	return entries
}

function toConstName(filename: string): string {
	const name = basename(filename, '.svg')
	return name
		.replace(/[^a-zA-Z0-9]+/g, '_')
		.replace(/^[0-9]/, '_$&')
		.toUpperCase()
}

function extractPaths(svgContent: string): string[] {
	const matches = svgContent.match(/\sd="([MmCcLlHhVvZzSsQqTtAa][^"]+)"/g) ?? []
	return matches.map((m) => m.match(/d="([^"]+)"/)?.[1] ?? '').filter(Boolean)
}

const files = findSvg(svgDir)
files.sort()

const blocks: string[] = ['// AUTO-GENERATED by scripts/svg-paths.ts — do not edit manually']

for (const file of files) {
	const content = readFileSync(file, 'utf8')
	const paths = extractPaths(content)
	const constName = toConstName(basename(file))

	const strings = paths.map((d) => {
		const points = svgRail(d)
		return railToString(points)
	})

	const lines = strings.map((s) => `\t'${s}',`).join('\n')
	blocks.push(`export const ${constName}: string[] = [\n${lines}\n]`)
}

const out = blocks.join('\n\n') + '\n'
writeFileSync(outFile, out)
console.log(`Wrote ${files.length} file(s) to ${outFile}`)

// Format with prettier
execSync(`npx prettier --write "${outFile}"`, { stdio: 'inherit' })
