// Scans resources/svg/**/*.svg and writes src/scenes/utils/svg-paths.ts
// Each SVG file → one const with path `d` attributes parsed via svgRail + serialized with railToString
import { readdirSync, statSync, readFileSync, writeFileSync } from 'fs'
import { join, basename, extname } from 'path'
import { execSync } from 'child_process'
import { svgRail } from '../src/lib/core/rail-primitives'
import { railToString } from '../src/lib/core/rail-path'
import chokidar from 'chokidar'
import PATHS from '../src/scenes/utils/svg-paths'

const svgDir = new URL('../resources/svg', import.meta.url).pathname
const outFile = new URL('../src/scenes/utils/svg-paths.ts', import.meta.url).pathname

function findSvg(dir: string): string[] {
	const entries: string[] = []
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry)
		if (statSync(full).isDirectory()) {
			entries.push(...findSvg(full))
		} else if (extname(entry) === '.svg') {
			entries.push(full)
		}
	}
	return entries
}

function toConstName(filename: string): string {
	const name = basename(filename, '.svg')
	return name
		.replace(/[^a-zA-Z0-9]+/g, '_')
		.replace(/^[0-9]/, '_$&')
		.toUpperCase()
}

function extractPathsOld(svgContent: string): string[] {
	const matches = svgContent.match(/\sd="([MmCcLlHhVvZzSsQqTtAa][^"]+)"/g) ?? []
	return matches.map((m) => m.match(/d="([^"]+)"/)?.[1] ?? '').filter(Boolean)
}

function extractPaths(svgContent: string): { d: string; id?: string }[] {
	const pathTags = svgContent.match(/<path\b[^>]*>/gi) ?? []

	return <{ d: string; id?: string }[]>pathTags
		.map((tag) => {
			const d = tag.match(/\bd="([^"]+)"/)?.[1]
			const id = tag.match(/\bid="([^"]+)"/)?.[1]

			return d ? { d, id } : null
		})
		.filter((v) => Boolean(v))
}

const blocks: string[] = ['// AUTO-GENERATED by scripts/svg-paths.ts — do not edit manually']
const vars: Record<string, Record<string, string>> = PATHS

function convertDir(file?: string) {
	if (!file || file === '--watch') {
		console.log(`Reading directory ${svgDir}`)
	}

	const files = file && file !== '--watch' ? [file] : findSvg(svgDir)
	files.sort()

	for (const file of files) {
		console.log(`Reading file ${file}`)
		const content = readFileSync(file, 'utf8')
		const paths = extractPaths(content)
		const constName = toConstName(basename(file))

		console.log(`Found ${paths.length} paths`)

		vars[constName] = Object.fromEntries(
			paths.map(({ d, id }, i) => {
				// console.log(`Converting path ${d}`)
				const points = svgRail(d)
				// console.log(`Stringifying points ${points}`)
				return [id ?? `id${i}`, railToString(points)]
			})
		)
	}

	const out =
		[
			...blocks,
			...Object.entries(vars).map(([constName, strings]: [string, Record<string, string>]) => {
				const lines = Object.entries(strings)
					.map(([id, s]) => `\t\'${id}\': '${s}',`)
					.join('\n')
				return `export const ${constName}: Record<string, string> = {\n${lines}\n}`
			}),
			`export default { ${Object.keys(vars).join(', ')} }`
		].join('\n\n') + '\n'
	writeFileSync(outFile, out)
	console.log(`Wrote ${files.length} file(s) to ${outFile}`)

	if (!file) {
		// Format with prettier
		execSync(`npx prettier --write "${outFile}"`, { stdio: 'inherit' })
	}
}

convertDir(process.argv[2])

if (process.argv[2] === '--watch') {
	console.log('watching', svgDir)
	const watcher = chokidar.watch(svgDir, {
		persistent: true
	})

	watcher.on('change', (path) => {
		console.log('change', path)
		convertDir(path)
	})
}
