// RNBO entry point — extracted from webpack bundle
// Auto-generated by scripts/rnbo-deobfuscate.ts

import workletJsUrl from './worklet-js.js?worker&url'
import workletWasmUrl from './worklet-wasm.js?worker&url'
import * as _845 from 'pako'
var r = () => _845
import * as n from './rnbo-enums.js'
import * as i from './rnbo-data-buffer.js'
import * as s from './rnbo-platform.js'
import * as a from './rnbo-parameters.js'
import * as o from './rnbo-parameter-types.js'
import * as u from './rnbo-events.js'
const h = {
	notificationSetting: o.E.All
}
class f {
	constructor(t) {
		this.tt = new Map()
		this.et = new Map()
		this.id = (0, s.EL)()
		this.parameterChangeEvent = new s.BM()
		this.rt = (t) => {
			const e = this.tt.get(t.target)
			if (!e) {
				return
			}
			const r = t.value
			if (e.type === o.r.Bang || r !== e.value) {
				e.$(r)
				this.parameterChangeEvent.emit(e)
			}
		}
		this.nt = (t) => {
			const e = t.index
			const r = t.type === o.r.Bang ? 1 : t.value
			const n = new u.DB(0, e, r, this.id, undefined)
			if (this.it) {
				this.it.scheduleEvent(n)
			}
			if (this.notificationSetting === o.E.All) {
				this.parameterChangeEvent.emit(t)
			}
		}
		const e = Object.assign({}, h, t)
		this.X = e.notificationSetting
	}
	st(t) {
		return this.tt.get(t) || undefined
	}
	ot() {
		for (const t of this.tt.values()) {
			t.L.removeAllSubscriptions()
			t.changeEvent.removeAllSubscriptions()
		}
		this.tt.clear()
		this.et.clear()
	}
	ut() {
		if (!this.it) {
			throw new Error('Cannot populate ParameterInterface without setting engine first.')
		}
		this.ot()
		for (let t = 0, e = this.it.getNumParameters(); t < e; t++) {
			const e = this.it.getParameterInfo(t)
			if (!e) {
				continue
			}
			if (!e.visible) {
				continue
			}
			const r = (0, a.zT)(e, t, this.notificationSetting, {
				convertFromNormalized: this.it.getParameterFromNormalizedFunction(t),
				convertToNormalized: this.it.getParameterToNormalizedFunction(t),
				constrainParameterValue: this.it.constrainParameterValue(t)
			})
			r.L.subscribe(this.nt)
			this.tt.set(t, r)
			this.et.set(e.id, r)
		}
	}
	setEngine(t) {
		if (this.it) {
			throw new Error("ParamInterface already has an engine, which can't be overridden.")
		}
		this.it = t
		this.it.parameterChangeEvent.subscribe(this.rt)
		this.ut()
	}
	get notificationSetting() {
		return this.X
	}
	set notificationSetting(t) {
		for (const e of this.tt.values()) {
			e.W(t)
		}
		this.X = t
	}
	get numParameters() {
		return this.tt.size
	}
	get parameters() {
		return Array.from(this.tt.values())
	}
	get parametersById() {
		return this.et
	}
	getParameterName(t) {
		const e = this.st(t)
		if (e) {
			return e.name
		} else {
			return undefined
		}
	}
	destroy() {
		this.it.parameterChangeEvent.unsubscribe(this.rt)
		this.it = undefined
		this.ot()
		this.parameterChangeEvent.removeAllSubscriptions()
	}
}
var c
function l(t) {
	return t.file !== undefined
}
function p(t) {
	return t.url !== undefined
}
;(function (t) {
	t[(t.AudioBuffer = 1)] = 'AudioBuffer'
	t[(t.DataBuffer = 2)] = 'DataBuffer'
	t[(t.ReferenceBuffer = 3)] = 'ReferenceBuffer'
})((c ||= {}))
var d
import { Buffer as g } from 'buffer'
;(function (t) {
	t.Script = 'script'
	t.Worklet = 'worklet'
	t.Invalid = 'invalid'
})((d ||= {}))
class m {
	constructor({ context: t, parameterNotificationSetting: e, type: r }) {
		this.ht = false
		this.ft = 'wasm'
		this.ct = new s.e1()
		this.lt = true
		this.midiEvent = new s.BM()
		this.messageEvent = new s.BM()
		this.parameterChangeEvent = new s.BM()
		this.invalidateEvent = new s.BM()
		this.presetTouchedEvent = new s.BM()
		this.dt = (t) => {
			switch (t.type) {
				case u.m5.ClockEvent:
				case u.m5.DataRefEvent:
				case u.m5.StartupEvent:
					break
				case u.m5.MIDIEvent:
					this.midiEvent.emit(t)
					return
				case u.m5.MessageEvent:
					this.messageEvent.emit(t)
					return
				case u.m5.PresetEvent:
					if (t.action == u.l0.Touched) {
						this.presetTouchedEvent.emit()
						return
					}
				default:
					console.error(t)
					throw new Error(`Unknown or unsupported RNBOEvent type "${t.type}"`)
			}
		}
		this.gt = (t) => {
			this.parameterChangeEvent.emit(t)
		}
		this._t = t
		this.yt = r
		this.F = new f({
			notificationSetting: e
		})
	}
	vt() {
		if (this.ht) {
			throw new Error(
				'Error while trying to overwrite immutable patcher of an existing device. Please create a new Device using RNBO.createDevice instead.'
			)
		}
	}
	It(t, e, r) {
		if (this.it) {
			this.it.prepareToProcess(t, e, r)
		}
	}
	wt() {
		if (this.isInvalid) {
			throw new Error(
				'Error: This device has become invalid due to creating a new device from it and is therefore unusable.'
			)
		}
	}
	Et(t) {
		const e = g.from(t.code, t.encoding)
		if (t.compression === 'zlib') {
			return r().inflate(e, {
				to: 'string'
			})
		} else {
			return e.toString('utf-8')
		}
	}
	get context() {
		this.wt()
		return this._t
	}
	get inports() {
		this.wt()
		return this.it.getMessageInfos().filter((t) => t.type === n.s.Inport)
	}
	get isValid() {
		return this.lt
	}
	get isInvalid() {
		return !this.lt
	}
	get numInputChannels() {
		this.wt()
		if (this.it) {
			return this.it.getNumInputChannels()
		} else {
			return 0
		}
	}
	get numOutputChannels() {
		this.wt()
		if (this.it) {
			return this.it.getNumOutputChannels()
		} else {
			return 0
		}
	}
	get numMIDIInputPorts() {
		this.wt()
		if (this.it) {
			return this.it.getNumMIDIInputPorts()
		} else {
			return 0
		}
	}
	get numMIDIOutputPorts() {
		this.wt()
		if (this.it) {
			return this.it.getNumMIDIOutputPorts()
		} else {
			return 0
		}
	}
	get numParameters() {
		this.wt()
		return this.F.numParameters
	}
	get outports() {
		this.wt()
		return this.it.getMessageInfos().filter((t) => t.type === n.s.Outport)
	}
	get parameters() {
		this.wt()
		return this.F.parameters
	}
	get messages() {
		this.wt()
		return this.it.getMessageInfos()
	}
	get parametersById() {
		this.wt()
		return this.F.parametersById
	}
	get parameterNotificationSetting() {
		this.wt()
		return this.F.notificationSetting
	}
	set parameterNotificationSetting(t) {
		this.wt()
		this.F.notificationSetting = t
	}
	get sourceType() {
		return this.ft
	}
	get type() {
		if (this.isInvalid) {
			return d.Invalid
		} else {
			return this.yt
		}
	}
	get dataBufferIds() {
		return this.it.getExternalDataRefIds()
	}
	get dataBufferDescriptions() {
		return this.it.getExternalDataRefInfos()
	}
	async setDataBuffer(e, r, n, s) {
		if (!this.dataBufferDescriptions.find((t) => t.id === e)) {
			throw new Error(
				`Unknown DataBuffer id. A DataBuffer with the id "${e}" does not exist within the device.`
			)
		}
		let t
		let a
		if (r instanceof AudioBuffer) {
			a = i.Le.fromAudioBuffer(r)
			const e = r.numberOfChannels
			const n = new Float32Array(r.length * r.numberOfChannels)
			const s = []
			for (let t = 0; t < e; t++) {
				const e = new Float32Array(r.length)
				r.copyFromChannel(e, t, 0)
				s.push(e)
			}
			for (let t = 0; t < e; t++) {
				for (let i = 0, a = r.length; i < a; i++) {
					n[i * e + t] = s[t][i]
				}
			}
			t = n.buffer
		} else {
			if (!n || n < 0 || isNaN(n)) {
				throw new Error('Invalid channel count. Expecting a numeric value >= 1')
			}
			if (!s || s < 0 || isNaN(s)) {
				throw new Error('Invalid sample rate. Expecting a numeric value >= 1')
			}
			t = ArrayBuffer.isView(r) ? r.buffer.slice(0) : r.slice(0)
			a = new i.Le(n, s)
		}
		await this.it.setExternalData(e, t, a)
	}
	async releaseDataBuffer(e) {
		if (!this.dataBufferDescriptions.find((t) => t.id === e)) {
			throw new Error(
				`Unknown DataBuffer id. A DataBuffer with the id "${e}" does not exist within the device.`
			)
		}
		const { data: t, typeDesc: r } = await this.it.releaseExternalData(e)
		return new i.OM(t, r)
	}
	static async fetchAudioData(e, r) {
		let t = await fetch(e)
		let n = await t.arrayBuffer()
		return new Promise((t, e) => {
			r.decodeAudioData(n, t, e)
		})
	}
	static bufferDescriptionHasRemoteURL(t) {
		return !!p(t) || (!!l(t) && (!!t.file.startsWith('http:') || !!t.file.startsWith('https:')))
	}
	async loadDataBufferDependencies(e) {
		return Promise.all(
			e.map(async (e) => {
				try {
					let t
					if (p(e)) {
						t = e.url
					} else if (l(e)) {
						t = e.file
					}
					if (t) {
						const r = await m.fetchAudioData(t, this.context)
						this.setDataBuffer(e.id, r)
						return {
							type: 'success',
							id: e.id
						}
					}
					throw new Error(`Skipping invalid buffer info id: ${e.id}, type: ${e.type}`)
				} catch (t) {
					return {
						type: 'fail',
						error: t,
						id: e.id
					}
				}
			})
		)
	}
	scheduleEvent(t) {
		this.wt()
		if (this.it) {
			this.it.scheduleEvent(t)
		}
	}
	destroy() {
		this.wt()
		this.F.destroy()
		if (this.it) {
			this.it.invalidateProcessor()
			this.it.removeAllSubscriptions()
		}
		this.it = undefined
		if (this.Mt) {
			this.Mt.disconnect()
		}
		this.Mt = undefined
		delete this.F
		delete this.ct
		delete this._t
		this.lt = false
		this.invalidateEvent.emit()
		this.invalidateEvent.removeAllSubscriptions()
		this.messageEvent.removeAllSubscriptions()
		this.midiEvent.removeAllSubscriptions()
		this.parameterChangeEvent.removeAllSubscriptions()
	}
	async getPreset() {
		return this.it.getPreset()
	}
	setPreset(t) {
		return this.it.setPreset(t)
	}
}
import * as _ from './rnbo-base-engine.js'
import y from './rnbo-runtime-helpers.js'
import v from './rnbo-default-patcher.js'
function b(t, e) {
	return t.time - e.time
}
function I(t) {
	t.sort(b)
}
class w extends _.v {
	constructor() {
		super()
		this.At = false
		this.Tt = false
		this.St = undefined
		this.Bt = -1
		this.Pt = []
		this.At = false
		this.setPatcherDesc(v.desc)
		this.setPatcherCode(v.src[0].code)
	}
	Rt(t) {
		const e = t.eventTarget || this.Dt
		t.time = Math.max(t.time, this.I)
		this.St = t
		if (t.type === u.m5.ParameterEvent) {
			const r = t
			e.setParameterValue(r.target, r.value, t.time)
		} else if (t.type === u.m5.ParameterBangEvent) {
			const r = t
			e.processParameterBangEvent(r.target, t.time)
		} else if (t.type === u.m5.MIDIEvent) {
			const r = t
			e.processMidiEvent(r.time, r.port, r.data, r.length)
		} else if (t.type === u.m5.ClockEvent) {
			const r = t
			e.processClockEvent(r.time, r.clockIndex, r.hasValue, r.value)
		} else if (t.type === u.m5.DataRefEvent) {
			const r = t
			if (r.action === u.VH.Update) {
				e.processDataViewUpdate(r.dataRefIndex, r.time)
			}
		} else if (t.type === u.m5.MessageEvent) {
			const r = t
			if (Array.isArray(r.payload)) {
				e.processListMessage(y.TAG(r.tag), y.TAG(r.objectId), r.time, r.payload)
			} else if (r.payload === undefined) {
				e.processBangMessage(y.TAG(r.tag), y.TAG(r.objectId), r.time)
			} else {
				e.processNumMessage(y.TAG(r.tag), y.TAG(r.objectId), r.time, r.payload)
			}
		} else if (t.type === u.m5.PresetEvent) {
			const e = t
			if (e.action === u.l0.Set) {
				this.Tt = true
				this.Dt.setPreset(e.time, e.preset)
				this.Tt = false
			}
		} else if (t.type === u.m5.TransportEvent) {
			const e = t
			this.Dt.processTransportEvent(e.time, e.state)
		} else if (t.type === u.m5.TempoEvent) {
			const e = t
			this.Dt.processTempoEvent(e.time, e.tempo)
		} else if (t.type === u.m5.BeatTimeEvent) {
			const e = t
			this.Dt.processBeatTimeEvent(e.time, e.beattime)
		} else if (t.type === u.m5.TimeSignatureEvent) {
			const e = t
			this.Dt.processTimeSignatureEvent(e.time, e.numerator, e.denominator)
		} else if (t.type === u.m5.StartupEvent) {
			const e = t
			this.Tt = e.phase === u.gA.BEGIN
		}
		this.St = undefined
	}
	getCurrentTime() {
		return this.I
	}
	setCurrentTime(t) {
		this.I = t
	}
	prepareToProcess(t, e, r) {
		if (r || t !== this.M || e !== this.A) {
			this.M = t
			this.A = e
			this.T = this.sampsToMs(this.A)
			if (this.isSync) {
				this.Dt.prepareToProcess(this.M, this.A)
			}
		}
	}
	process(t, e, r, n, i, s, a) {
		const o = Math.min(e, this.getNumInputChannels() + this.getNumSignalInParameters())
		const u = Math.min(n, this.getNumOutputChannels())
		const h = Math.min(i, this.A)
		this.Bt = this.I + this.T
		if (this.midiInput !== undefined) {
			this.Pt.push.apply(this.Pt, s)
			this.At = true
		}
		if (this.At) {
			I(this.Pt)
			this.At = false
		}
		while (this.Pt.length > 0 && this.Pt[0].time < this.Bt) {
			this.Rt(this.Pt.shift())
		}
		this.Dt.process(t, o, r, u, h)
		this.I = this.Bt
		this.Bt = -1
	}
	scheduleMidiEvent(t, e) {
		this.scheduleEvent(new u.Ym(this.I, t, e, this.Dt))
	}
	notifyParameterValueChanged(t, e) {
		let r = this.St ? this.St.source : undefined
		this.parameterChangeEvent.emit(new u.DB(this.getCurrentTime(), t, e, r))
	}
	scheduleParameterChange(t, e, r) {
		this.scheduleEvent(new u.DB(this.getCurrentTime(), t, e, undefined))
	}
	scheduleParameterBang(t, e) {
		this.scheduleEvent(new u.zz(this.getCurrentTime(), t))
	}
	sendNumMessage(t, e, r) {
		const n = new u.f3(this.I, this.Dt.resolveTag(t), r, this.Dt.resolveTag(e))
		this.outgoingEvent.emit(n)
	}
	sendBangMessage(t, e) {
		const r = new u.f3(this.I, this.Dt.resolveTag(t), undefined, this.Dt.resolveTag(e))
		this.outgoingEvent.emit(r)
	}
	sendListMessage(t, e, r) {
		const n = new u.f3(this.I, this.Dt.resolveTag(t), r, this.Dt.resolveTag(e))
		this.outgoingEvent.emit(n)
	}
	getParameterValue(t) {
		return this.Dt.getParameterValue(t)
	}
	flushClockEvents(t, e, r) {
		this.flushClockEventsWithValue(t, e, undefined, r)
	}
	flushClockEventsWithValue(t, e, r, n) {
		for (let i = 0; i < this.Pt.length; i++) {
			if (this.Pt[i] instanceof u.J9) {
				const s = this.Pt[i]
				if (
					s.eventTarget === t &&
					(s.clockIndex === e || s.clockIndex === undefined) &&
					(r === undefined || s.value === r)
				) {
					this.Pt.splice(i, 1)
					if (n) {
						this.Rt(s)
					}
					i--
				}
			}
		}
	}
	deleteClockEvents(t) {
		this.flushClockEvents(t, undefined, false)
	}
	scheduleClockEvent(t, e, r) {
		this.scheduleClockEventWithValue(t, e, r, undefined)
	}
	scheduleClockEventWithValue(t, e, r, n) {
		this.scheduleEvent(new u.J9(r, e, n, t))
	}
	sendMidiEvent(t, e, r, n) {
		const i = new u.Ym(this.getCurrentTime(), t, [e, r, n], undefined)
		this.outgoingEvent.emit(i)
	}
	sendMidiEventList(t, e) {
		let r
		for (r = 2; r < e.length; r += 3) {
			this.sendMidiEvent(t, e[r - 2], e[r - 1], e[r])
		}
		r -= 3
		if (r < e.length) {
			var n = r - e.length
			this.sendMidiEvent(t, e[r], n > 1 ? e[r + 1] : undefined, n > 2 ? e[r + 2] : undefined)
		}
	}
	sendOutlet(t, e, r) {
		console.log('sendOutlet', t, e, r)
	}
	updatePatcherEventTarget(t, e) {
		for (let r = 0; r < this.Pt.length; r++) {
			if (this.Pt[r].eventTarget === t) {
				this.Pt[r].eventTarget = e
				this.Pt[r].invalid = false
			}
		}
	}
	rescheduleEventTarget(t) {
		for (let e = 0; e < this.Pt.length; e++) {
			if (this.Pt[e].eventTarget === t) {
				this.Pt[e].invalid = false
			}
		}
	}
	isInProcess() {
		return this.Bt > -1
	}
	sendDataRefUpdated(t) {
		this.scheduleEvent(new u.Lk(this.getCurrentTime(), t, u.VH.Update, this.Dt))
	}
	get isSync() {
		return true
	}
	scheduleEvent(t) {
		this.Pt.push(t)
		if (this.isInProcess()) {
			I(this.Pt)
		} else {
			this.At = true
		}
	}
	async setPatcherCode(e) {
		const t = {}
		if (this.Dt) {
			this.Dt.extractState(t)
		}
		this.Dt = y.deserializeSrc(e)
		for (let t = 0; t < this.Pt.length; t++) {
			if (this.Pt[t].eventTarget) {
				this.Pt[t].invalid = true
			}
		}
		this.Dt.setEngineAndPatcher(this, null)
		this.scheduleEvent(new u.j6(this.I, u.gA.BEGIN))
		this.Dt.initialize(t)
		this.scheduleEvent(new u.j6(this.I, u.gA.END))
		this.Dt.prepareToProcess(this.M, this.A, true)
		for (let t = this.Pt.length - 1; t >= 0; t--) {
			if (this.Pt[t].invalid) {
				this.Pt.splice(t, 1)
			}
		}
	}
	async setExternalData(e, r, n) {
		const t = this.Dt.getNumDataRefs()
		for (let s = 0; s < t; s++) {
			const t = this.Dt.getDataRef(s)
			if (t.name == e) {
				t.arrayBuffer = r
				if (n instanceof i.Le) {
					t.channels = n.channels
					t.sampleRate = n.sampleRate
				}
				this.sendDataRefUpdated(s)
				break
			}
		}
	}
	async releaseExternalData(e) {
		const t = this.Dt.getNumDataRefs()
		let r
		let n
		for (let s = 0; s < t; s++) {
			const t = this.Dt.getDataRef(s)
			if (t.name == e) {
				r = t.arrayBuffer
				t.arrayBuffer = new ArrayBuffer(0)
				if (t.channels) {
					n = new i.Le(t.channels, t.sampleRate)
					t.channels = 0
					t.sampleRate = 0
				} else {
					n = new i.nc()
				}
				this.sendDataRefUpdated(s)
				break
			}
		}
		if (!r) {
			throw new Error(`Invalid DataBuffer. No DataBuffer with id ${e} found.`)
		}
		return {
			data: r,
			typeDesc: n
		}
	}
	async getPreset() {
		let t = {}
		this.Dt.getPreset(t)
		return t
	}
	setPreset(t) {
		this.scheduleEvent(new u.bt(this.I, u.l0.Set, t))
	}
	presetTouched() {
		if (!this.Tt) {
			this.outgoingEvent.emit(new u.bt(this.I, u.l0.Touched, undefined))
		}
	}
}
var E
var M
import * as A from './rnbo-wasm-engine.js'
class T extends m {
	constructor({ bufferSize: t = 1024, context: e, parameterNotificationSetting: r }, n) {
		super({
			context: e,
			parameterNotificationSetting: r,
			type: d.Script
		})
		this.bufferSize = t
		this.it = n && n.sourceType !== 'wasm' ? n.it : undefined
	}
	Ot(t) {
		const e = []
		const r = []
		const n = t.inputBuffer
		const i = t.outputBuffer
		const s = n ? n.numberOfChannels : 0
		const a = i ? i.numberOfChannels : 0
		for (let t = 0; t < Math.max(s, a); t++) {
			if (t < s) {
				e[t] = n.getChannelData(t)
			}
			if (t < a) {
				r[t] = i.getChannelData(t)
			}
		}
		this.Nt(t.playbackTime * 1000)
		this.It(t.outputBuffer.sampleRate, this.bufferSize, false)
		this.Ct(e, s, r, a, this.bufferSize, null, null)
	}
	Ct(t, e, r, n, i, s, a) {
		if (this.it) {
			this.it.process(t, e, r, n, i, s || undefined, a || undefined)
		}
	}
	Nt(t) {
		if (this.it) {
			this.it.setCurrentTime(t)
		}
	}
	get node() {
		this.wt()
		return this.Mt
	}
	async setPatcher(e, r) {
		this.vt()
		this.it ||= r.type === 'wasm' ? new A.s() : new w()
		this.ft = r.type
		await this.it.setPatcherDesc(e)
		await this.it.setPatcherCode(this.Et(r))
		this.F.setEngine(this.it)
		this.F.parameterChangeEvent.subscribe(this.gt)
		this.it.outgoingEvent.subscribe(this.dt)
		this.Mt = this.context.createScriptProcessor(
			this.bufferSize,
			this.numInputChannels,
			Math.max(this.numOutputChannels, 1)
		)
		this.node.onaudioprocess = this.Ot.bind(this)
	}
}
;(function (t) {
	t[(t.LoadPatcher = 0)] = 'LoadPatcher'
	t[(t.ScheduleEvent = 1)] = 'ScheduleEvent'
	t[(t.TransferBuffer = 2)] = 'TransferBuffer'
	t[(t.ReleaseBuffer = 3)] = 'ReleaseBuffer'
	t[(t.SetPreset = 4)] = 'SetPreset'
	t[(t.GetPreset = 5)] = 'GetPreset'
	t[(t.Invalidate = 6)] = 'Invalidate'
})((E ||= {}))
;(function (t) {
	t[(t.LoadPatcherFinished = 1000)] = 'LoadPatcherFinished'
	t[(t.OutgoingEvent = 1002)] = 'OutgoingEvent'
	t[(t.ReleasedBuffer = 1003)] = 'ReleasedBuffer'
	t[(t.TransferBufferFinished = 1004)] = 'TransferBufferFinished'
	t[(t.GetPresetResponse = 1005)] = 'GetPresetResponse'
})((M ||= {}))
class S extends _.v {
	constructor() {
		super()
		this.kt = new s.BM()
		this.xt = new s.BM()
		this.Ut = (t) => {
			if (t.id !== M.OutgoingEvent || t.payload.type !== u.m5.ParameterEvent) {
				if (t.id !== M.OutgoingEvent) {
					if (
						t.id !== M.LoadPatcherFinished &&
						t.id !== M.TransferBufferFinished &&
						t.id !== M.ReleasedBuffer &&
						t.id !== M.GetPresetResponse
					) {
						throw new Error(`Unhandled RNBOProcessor event with type ${t.id}`)
					}
				} else {
					this.outgoingEvent.emit(t.payload)
				}
			} else {
				this.parameterChangeEvent.emit(t.payload)
			}
		}
		this.kt.subscribe(this.Ut)
	}
	get eventSubjects() {
		return {
			fromProcessorEvent: this.kt,
			toProcessorEvent: this.xt
		}
	}
	notifyParameterValueChanged(t, e, r, n) {
		this.parameterChangeEvent.emit(new u.DB(t, e, r, n, undefined))
	}
	prepareToProcess(t, e, r) {}
	process(t, e, r, n, i, s, a) {
		throw new Error()
	}
	get isSync() {
		return false
	}
	scheduleEvent(t) {
		this.xt.emit({
			id: E.ScheduleEvent,
			payload: t
		})
	}
	setExternalData(t, e, r) {
		return new Promise((n, i) => {
			const s = this.kt.subscribe((e) => {
				if (e.id === M.TransferBufferFinished && e.payload.memoryId === t) {
					s.unsubscribe()
					n()
				}
			})
			this.xt.emit({
				id: E.TransferBuffer,
				payload: {
					memoryId: t,
					data: e,
					typeDesc: r
				}
			})
		})
	}
	releaseExternalData(t) {
		return new Promise((e, r) => {
			const n = this.kt.subscribe((r) => {
				if (r.id === M.ReleasedBuffer && r.payload.memoryId === t) {
					n.unsubscribe()
					e({
						data: r.payload.data,
						typeDesc: (0, i.n_)(r.payload.typeDesc)
					})
				}
			})
			this.xt.emit({
				id: E.ReleaseBuffer,
				payload: {
					memoryId: t
				}
			})
		})
	}
	async getPreset() {
		return new Promise((t, e) => {
			const r = this.kt.subscribe((e) => {
				if (e.id === M.GetPresetResponse) {
					r.unsubscribe()
					t(e.payload.preset)
				}
			})
			this.xt.emit({
				id: E.GetPreset
			})
		})
	}
	setPreset(t) {
		this.xt.emit({
			id: E.SetPreset,
			payload: {
				preset: t
			}
		})
	}
	async setPatcherCode(e) {}
	removeAllSubscriptions() {
		super.removeAllSubscriptions()
		this.xt.removeAllSubscriptions()
		this.kt.removeAllSubscriptions()
	}
	invalidateProcessor() {
		this.xt.emit({
			id: E.Invalidate
		})
	}
}
const B = () => {
	if (!s.I7) {
		throw new Error('Missing AudioWorklet Support')
	}
	return class extends AudioWorkletNode {
		constructor(t, e, r, n) {
			super(t, e, n)
			this.zt = (t) => {
				const [e, r] = t.data
				if (e !== M.OutgoingEvent) {
					if (e !== M.LoadPatcherFinished) {
						if (e !== M.TransferBufferFinished) {
							if (e !== M.ReleasedBuffer) {
								if (e !== M.GetPresetResponse) {
									throw new Error(`Unable to handle received processor message of type ${e}`)
								}
								this.jt.fromProcessorEvent.emit({
									id: e,
									payload: r
								})
							} else {
								this.jt.fromProcessorEvent.emit({
									id: e,
									payload: r
								})
							}
						} else {
							this.jt.fromProcessorEvent.emit({
								id: e,
								payload: r
							})
						}
					} else {
						this.jt.fromProcessorEvent.emit({
							id: e,
							payload: r
						})
					}
				} else {
					this.jt.fromProcessorEvent.emit({
						id: e,
						payload: (0, u.f4)(r)
					})
				}
			}
			this.Ft = (t) => {
				if (t.id !== E.ScheduleEvent) {
					if (t.id !== E.TransferBuffer) {
						if (t.id !== E.ReleaseBuffer) {
							if (t.id !== E.GetPreset) {
								if (t.id !== E.SetPreset) {
									if (t.id === E.Invalidate) {
										this.port.postMessage([t.id])
									}
								} else {
									this.port.postMessage([
										t.id,
										{
											preset: t.payload.preset
										}
									])
								}
							} else {
								this.port.postMessage([t.id])
							}
						} else {
							this.port.postMessage([
								t.id,
								{
									memoryId: t.payload.memoryId
								}
							])
						}
					} else {
						this.port.postMessage(
							[
								t.id,
								{
									data: t.payload.data,
									memoryId: t.payload.memoryId,
									typeDesc: t.payload.typeDesc.serialize()
								}
							],
							[t.payload.data]
						)
					}
				} else {
					this.port.postMessage([t.id, t.payload.serialize()])
				}
			}
			this.jt = r
			this.jt.toProcessorEvent.subscribe(this.Ft)
			this.port.onmessage = this.zt
			this.port.start()
		}
		async loadPatcher() {
			return new Promise((t) => {
				const e = this.jt.fromProcessorEvent.subscribe((r) => {
					if (r.id === M.LoadPatcherFinished) {
						e.unsubscribe()
						t()
					}
				})
				this.port.postMessage([E.LoadPatcher])
			})
		}
	}
}
var P = g
const R = v
const D = { js: workletJsUrl, wasm: workletWasmUrl }
class O extends m {
	constructor({ context: t, parameterNotificationSetting: e }, r) {
		super({
			context: t,
			parameterNotificationSetting: e,
			type: d.Worklet
		})
		if (r) {
			this.it = r.it
		} else {
			this.it = new S()
			this.it.setPatcherDesc(R.desc)
			this.it.setPatcherCode(R.src[0].code)
		}
		this.Mt = r ? r.node : undefined
	}
	Lt() {
		let t = '['
		const e = this.it.getNumParameters()
		let r = true
		for (let n = 0; n < e; n++) {
			const e = this.it.getParameterInfo(n)
			if (
				e &&
				e.type !== undefined &&
				e.type === y.ParameterTypeSignal &&
				e.ioType !== undefined &&
				e.ioType === y.IOTypeInput
			) {
				const n = e.min === undefined ? 0 : e.min
				const i = e.max === undefined ? 1 : e.max
				const s = e.initialValue === undefined ? 0 : e.initialValue
				if (!r) {
					t += ', '
				}
				t +=
					"{ name: '" +
					e.name +
					"', automationRate: 'a-rate', defaultValue : " +
					s +
					', minValue: ' +
					n +
					', maxValue: ' +
					i +
					'}'
				r = false
			}
		}
		t += ']'
		return t
	}
	get node() {
		this.wt()
		return this.Mt
	}
	async setPatcher(e, r) {
		if (!this.it) {
			throw new Error('Attempt to set patcher on a WorkletDevice without assigning engine first.')
		}
		this.vt()
		await this.it.setPatcherDesc(e)
		this.F.setEngine(this.it)
		this.it.outgoingEvent.subscribe(this.dt)
		this.it.prepareToProcess(this.context.sampleRate, 128, false)
		this.ft = r.type
		const t = await fetch(D[r.type].replace(/\?.*$/, '')).then((res) => res.text())
		let n = this.numInputChannels
		let i = this.numOutputChannels
		if (n < 1) {
			n = 1
		}
		if (i < 1) {
			i = 1
		}
		const a = `RNBOProcessor-${(0, s.EL)()}`
		const preamble = [
			`var RNBO_PROCESSOR_NAME = ${JSON.stringify(a)};`,
			`var RNBO_PARAM_DESCRIPTORS = ${this.Lt()};`
		]
		if (r.type === 'js') {
			preamble.push(
				`var RNBO_PATCHER_DESC = ${JSON.stringify(P.from(JSON.stringify(e), 'utf-8').toString('base64'))};`,
				`var RNBO_PATCHER_SRC = ${JSON.stringify(P.from(this.Et(r), 'utf-8').toString('base64'))};`
			)
		}
		let o = preamble.join('\n') + '\n' + t
		if (r.type === 'wasm') {
			o = this.Et(r) + '\n\n' + o
		}
		const u = URL.createObjectURL(
			new Blob([o], {
				type: 'text/javascript'
			})
		)
		await this.context.audioWorklet.addModule(u)
		this.Mt = new (B())(this.context, a, this.it.eventSubjects, {
			numberOfInputs: n,
			numberOfOutputs: 1,
			outputChannelCount: [i]
		})
		await this.Mt.loadPatcher()
		this.F.parameterChangeEvent.subscribe(this.gt)
	}
}
const N = { D: 0 }
const C = '1.4.2'
const k = {
	bufferSize: 1024,
	parameterNotificationSetting: a.EX.All
}
async function x(e, r) {
	var o
	{
		const { context: t, patcher: u, type: h = 'auto' } = e
		const f = u.desc?.meta?.rnboversion || u.desc.rnboVersion
		if (f !== C) {
			;(console.error || console.log)(
				`\nWarning: The patcher was exported with a RNBO version does not match the version of @rnbo/js:\n@rnbo/js\tv${C}\npatcher\t\tv${f}\nIn order to have full compatibility and avoid unexpected behavior please ensure that you use the version of @rnbo/js that matches the version of RNBO you used to export your patcher.`.trim()
			)
		}
		if (!u.src?.length || !Array.isArray(u.src)) {
			throw new Error(
				'Incompatible patcher. Please export you patch with a newer, matching version of RNBO or adjust the version of @rnbo/js you are using.'
			)
		}
		if (
			!new Set((o = u.src) === null || o === undefined ? undefined : o.map((t) => t.type)).has(
				'js'
			) &&
			!s.f8
		) {
			throw new Error(
				'Incompatible browser. RNBO requires WASM support in order to run your exported patch as a Device.'
			)
		}
		const c = u.src.find((t) => s.f8 && t.type === 'wasm') || u.src.find((t) => t.type === 'js')
		const l = Object.assign({}, k, e.options)
		if (!t) {
			throw new Error('Missing argument context')
		}
		if (h === d.Worklet && !s.I7) {
			throw new Error(
				"Failed to create WorkletDevice due to missing AudioWorklet support. Please use the Device.Script or 'auto' option instead"
			)
		}
		const p = h === 'auto' ? (s.I7 ? d.Worklet : d.Script) : h
		if (p !== d.Script && p !== d.Worklet) {
			throw new Error(
				`Unknown Device type ${p}. Please make sure to use either 'auto' or a valid DeviceType`
			)
		}
		let g
		if (p === d.Script) {
			if (r && !(r instanceof T)) {
				throw new Error(
					"Error: Creating a device from an existing device cannot alter the type of the device. Please make sure to use a consistent 'type' parameter."
				)
			}
			g = new T(
				{
					bufferSize: l.bufferSize,
					parameterNotificationSetting: l.parameterNotificationSetting,
					context: t
				},
				(r == null ? undefined : r.sourceType) === c.type ? r : undefined
			)
		} else if (p === d.Worklet) {
			if (r && !(r instanceof O)) {
				throw new Error(
					"Error: Creating a device from an existing device cannot alter the type of the device. Please make sure to use a consistent 'type' parameter."
				)
			}
			g = new O(
				{
					context: t,
					parameterNotificationSetting: l.parameterNotificationSetting
				},
				r
			)
		}
		if (r) {
			r.destroy()
		}
		g = g
		await g.setPatcher(u.desc, c)
		return g
	}
}

export const BangParameter = a.jN
export { m as BaseDevice }
export const BaseEvent = u.j4
export const BeatTimeEvent = u.J0
export const CommonParameterMixin = a.IR
export const DataBuffer = i.OM
export { d as DeviceType }
export const EnumParameter = a.V2
export const EventSubject = s.BM
export const EventType = u.m5
export const MIDIEvent = u.Ym
export const MessageEvent = u.f3
export const MessagePortType = n.s
export const NumberParameter = a.BX
export const ParameterNotificationSetting = a.EX
export const ParameterType = a.rH
export const PresetEvent = u.bt
export const RNBOPresetEventAction = u.l0
export { T as ScriptDevice }
export const TempoEvent = u.gs
export const TimeNow = N.D
export const TimeSignatureEvent = u.QU
export const TransportEvent = u.cr
export const TransportState = n.S
export { O as WorkletDevice }
export { x as createDevice }
export { C as version }
