// AUTO-GENERATED by scripts/samples.ts — do not edit manually

export interface SampleLoopInfo {
	loopStartSample: number
	loopEndSample: number
	sampleRate: number
}

export interface SampleMeta {
	sampleRate: number
	channels: number
	bitDepth?: number
	duration: number
}

export interface SampleEntry {
	path: string
	loop?: SampleLoopInfo
}

export const SAMPLE_META: Record<string, SampleMeta> = {
	acid: { sampleRate: 44_100, channels: 1, duration: 1.5048299319727891 }
}

export const SAMPLES: Record<string, Record<string, SampleEntry>> = {
	acid: {
		C4: {
			path: 'acid/C4.ogg',
			loop: { loopStartSample: 61_759, loopEndSample: 65_805, sampleRate: 44_100 }
		}
	}
}
