export default <Record<string, Record<string, number>>>(<unknown>{
	Synth: {
		volume: 0,
		detune: 0,
		portamento: 0,
		'envelope.attack': 0.005,
		'envelope.decay': 0.1,
		'envelope.release': 1,
		'envelope.sustain': 0.3
	},
	PluckSynth: {
		volume: 0,
		attackNoise: 1,
		dampening: 4000,
		resonance: 0.7,
		release: 1
	},
	MetalSynth: {
		volume: 0,
		detune: 0,
		portamento: 0,
		'envelope.attack': 0.001,
		'envelope.decay': 1.4,
		'envelope.release': 0.2,
		'envelope.sustain': 0.5,
		harmonicity: 5.1,
		octaves: 1.5,
		resonance: 4000
	},
	NoiseSynth: {
		volume: 0,
		'envelope.attack': 0.01,
		'envelope.decay': 0.1,
		'envelope.release': 1,
		'envelope.sustain': 0,
		'noise.fadeIn': 0,
		'noise.fadeOut': 0,
		'noise.playbackRate': 1
	},
	AMSynth: {
		volume: 0,
		detune: 0,
		portamento: 0,
		harmonicity: 3,
		'envelope.attack': 0.01,
		'envelope.decay': 0.01,
		'envelope.release': 0.5,
		'envelope.sustain': 1,
		'modulationEnvelope.attack': 0.5,
		'modulationEnvelope.decay': 0,
		'modulationEnvelope.release': 0.5,
		'modulationEnvelope.sustain': 1
	},
	FMSynth: {
		volume: 0,
		detune: 0,
		portamento: 0,
		harmonicity: 3,
		'envelope.attack': 0.01,
		'envelope.decay': 0.01,
		'envelope.release': 0.5,
		'envelope.sustain': 1,
		'modulationEnvelope.attack': 0.5,
		'modulationEnvelope.decay': 0,
		'modulationEnvelope.release': 0.5,
		'modulationEnvelope.sustain': 1
	},
	MembraneSynth: {
		volume: 0,
		detune: 0,
		portamento: 0,
		'envelope.attack': 0.001,
		'envelope.decay': 0.4,
		'envelope.release': 1.4,
		'envelope.sustain': 0.01,
		octaves: 10,
		pitchDecay: 0.05
	},
	MonoSynth: {
		volume: 0,
		detune: 0,
		portamento: 0,
		'envelope.attack': 0.005,
		'envelope.decay': 0.1,
		'envelope.release': 1,
		'envelope.sustain': 0.9,
		'filter.Q': 1,
		'filter.detune': 0,
		'filter.gain': 0,
		'filterEnvelope.attack': 0.6,
		'filterEnvelope.decay': 0.2,
		'filterEnvelope.release': 2,
		'filterEnvelope.sustain': 0.5,
		'filterEnvelope.baseFrequency': 200,
		'filterEnvelope.exponent': 2,
		'filterEnvelope.octaves': 3,
		'oscillator.detune': 0
	},
	DuoSynth: {
		volume: 0,
		detune: 0,
		portamento: 0,
		vibratoAmount: 0.5,
		vibratoRate: 5,
		harmonicity: 1.5
	},
	Compressor: { attack: 0.003, knee: 30, ratio: 12, release: 0.25, threshold: -24 },
	Reverb: { wet: 1, decay: 1.5, preDelay: 0.01 },
	PingPongDelay: { wet: 1, feedback: 0.5, delayTime: 0.25, maxDelay: 1 },
	Freeverb: { wet: 1, roomSize: 0.7, dampening: 3000 },
	BitCrusher: { wet: 1, bits: 4 },
	AutoFilter: {
		wet: 1,
		frequency: 1,
		depth: 1,
		baseFrequency: 200,
		octaves: 2.6,
		'filter.Q': 1
	},
	MultibandCompressor: {
		lowFrequency: 250,
		highFrequency: 2000,
		'low.ratio': 6,
		'low.threshold': -30,
		'low.release': 0.25,
		'low.attack': 0.03,
		'low.knee': 10,
		'mid.ratio': 3,
		'mid.threshold': -24,
		'mid.release': 0.03,
		'mid.attack': 0.02,
		'mid.knee': 16,
		'high.ratio': 3,
		'high.threshold': -24,
		'high.release': 0.03,
		'high.attack': 0.02,
		'high.knee': 16
	},
	OnePoleFilter: { frequency: 880 },
	EQ3: { high: 0, highFrequency: 2500, low: 0, lowFrequency: 400, mid: 0 },
	Limiter: { threshold: -12 },
	Panner: { pan: 0, channelCount: 1 },
	Solo: {},
	Sampler: {
		volume: 0,
		attack: 0,
		release: 0.1
	}
})
